### ISSUE TITLE
出现段错误

### ISSUE THREAD

**Issue by gengfeipeng** [Lmerengues/Qmazon#1]
Qt: Untested Windows version 10.0 detected!
"C:/Users/admin/Desktop/build-Qt_book2-Desktop_Qt_5_4_2_MinGW_32bit-Debug/debug"
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::basic_string: __pos (which is 1) > this->size() (which is 0)

**Comment by zhengyima** [comment]
bug最新版本已修复
